//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tccEntities : DbContext
    {
        public tccEntities()
            : base("name=tccEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<tb_acoesProjeto> tb_acoesProjeto { get; set; }
        public virtual DbSet<tb_atividade> tb_atividade { get; set; }
        public virtual DbSet<tb_atividadeResponsavel> tb_atividadeResponsavel { get; set; }
        public virtual DbSet<tb_comentarioAtividade> tb_comentarioAtividade { get; set; }
        public virtual DbSet<tb_etapa> tb_etapa { get; set; }
        public virtual DbSet<tb_funcaoProjeto> tb_funcaoProjeto { get; set; }
        public virtual DbSet<tb_prioridadeAtividade> tb_prioridadeAtividade { get; set; }
        public virtual DbSet<tb_projeto> tb_projeto { get; set; }
        public virtual DbSet<tb_projetoUsuarioFuncao> tb_projetoUsuarioFuncao { get; set; }
        public virtual DbSet<tb_statusAtividade> tb_statusAtividade { get; set; }
        public virtual DbSet<tb_statusEtapa> tb_statusEtapa { get; set; }
        public virtual DbSet<tb_statusProjeto> tb_statusProjeto { get; set; }
        public virtual DbSet<tb_tipoAcaoProjeto> tb_tipoAcaoProjeto { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
    }
}
