//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_atividade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_atividade()
        {
            this.tb_atividadeResponsavel = new HashSet<tb_atividadeResponsavel>();
            this.tb_comentarioAtividade = new HashSet<tb_comentarioAtividade>();
            this.tb_etapa = new HashSet<tb_etapa>();
        }
    
        public int id_atividade { get; set; }
        public int id_projeto { get; set; }


        [Required(AllowEmptyStrings = false, ErrorMessage = "Campo Obrigatório", ErrorMessageResourceName = null, ErrorMessageResourceType = null)]
        [StringLength(200, ErrorMessage = "O título deve conter entre {2} e {1} caracteres.", MinimumLength = 5)]
        [Display(Name = "Título:")]
        public string titulo { get; set; }


        [DataType(DataType.MultilineText)]
        [StringLength(8000, ErrorMessage = "Limite de caracteres excedido. Máximo 8000 caracteres!", MinimumLength = 0)]
        [Display(Name = "Descrição:")]
        public string descricao { get; set; }


        public System.DateTime data_criacao { get; set; }
        public int id_statusAtividade { get; set; }
        public string id_usuario { get; set; }
        public int sequencia { get; set; }

        public int id_prioridadeAtividade { get; set; }
    
        public virtual tb_prioridadeAtividade tb_prioridadeAtividade { get; set; }
        public virtual tb_projeto tb_projeto { get; set; }
        public virtual tb_statusAtividade tb_statusAtividade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_atividadeResponsavel> tb_atividadeResponsavel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_comentarioAtividade> tb_comentarioAtividade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_etapa> tb_etapa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_acoesProjeto> tb_acoesProjeto { get; set; }
    }
}
