//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_etapa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_etapa()
        {
            this.tb_atividade = new HashSet<tb_atividade>();
        }
    
        public int id_etapa { get; set; }
        public int id_projeto { get; set; }
        public string titulo { get; set; }
        public string descricao { get; set; }
        public int sequencia { get; set; }
        public System.DateTime data_inicio { get; set; }
        public System.DateTime data_fim { get; set; }
        public int id_statusEtapa { get; set; }
        public string id_usuario { get; set; }
    
        public virtual tb_projeto tb_projeto { get; set; }
        public virtual tb_statusEtapa tb_statusEtapa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_atividade> tb_atividade { get; set; }
    }
}
