//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_projeto
    {
        public int id_projeto { get; set; }
        public string titulo { get; set; }
        public string descricao { get; set; }
        public System.DateTime data_inicio { get; set; }
        public Nullable<System.DateTime> data_fim { get; set; }
        public short id_status { get; set; }
    }
}
