//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_projeto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_projeto()
        {
            this.tb_acoesProjeto = new HashSet<tb_acoesProjeto>();
            this.tb_atividade = new HashSet<tb_atividade>();
            this.tb_etapa = new HashSet<tb_etapa>();
            this.tb_projetoUsuarioFuncao = new HashSet<tb_projetoUsuarioFuncao>();
        }
    
        public int id_projeto { get; set; }   

        [Required]
        [StringLength(20, ErrorMessage = "O título de {0} deve conter entre {2} e {1} caracteres.", MinimumLength = 5)]
        [Display(Name = "Título:")]
        public string titulo { get; set; }

        [DataType(DataType.MultilineText)]
        [StringLength(8000, ErrorMessage = "Limite de caracteres excedido. Máximo 8000 caracteres!", MinimumLength = 0)]
        [Display(Name = "Descrição:")]
        public string descricao { get; set; }

        [Required]
        [Display(Name = "Início:")]
        public System.DateTime data_inicio { get; set; }
        [Required]
        [Display(Name = "Termino:")]
        public Nullable<System.DateTime> data_fim { get; set; }

        public int id_statusProjeto { get; set; }
        public string id_usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_acoesProjeto> tb_acoesProjeto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_atividade> tb_atividade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_etapa> tb_etapa { get; set; }
        public virtual tb_statusProjeto tb_statusProjeto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_projetoUsuarioFuncao> tb_projetoUsuarioFuncao { get; set; }
    }
}
